### ISSUE TITLE
New extend feature breaks including translations before i18n.js

### ISSUE THREAD

**Issue by jakemhiller** [fnando/i18n-js#391]
The new translation extending feature introduced in #354 broke the use case where the translation files are included before I18n.js. If you were doing that, you now get an error because `I18n.extend` isn't defined.

`Uncaught TypeError: I18n.extend is not a function`

This feature made it much easier to keep i18n.js integrated into a JS build, with the translation files included first.

I can attempt a pull request, but I'm not sure what the best solution is.

My initial ideas were:
1. Make the extending optional
2. Make the translation output templatable

I lean towards the second option as it solves the issue and gives more flexibility for how the translation files are used in various kinds of projects.

**Comment by PikachuEXE** [comment]
Why would `I18n.extend` become undefined?
Because it's not detecting the existing the `I18n` object & adding the method to it?

**Comment by 1st8** [comment]
Hey, 
I got the same issue today when upgrading from rc11 to rc12.
I am bundling i18n.js into my main js file and loading the translations depending on current locale before that.
This results in I18n.extend not being available when the translation file is processed.

```html
    <script src="/assets/i18n/de-d4582a091c6a984386c5bc2a8f9b3611.js"></script>
    <script src="/assets/application-64dbf72160f28757ea63a8148cddd595.js"></script>
```

I have no good idea to solving this right now, I could supply my own implementation of `I18n.extend`, but that feels more like a hack.
In the meantime I will go back to using rc11.

**Comment by jakemhiller** [comment]
Sorry @PikachuEXE, yes, @1st8 has the same use case as me. `i18n.js` is included after the translation files, which reference `I18n.extend`.

**Comment by PikachuEXE** [comment]
@AntiFish03 Can you take a look and try to figure out what goes wrong?

**Comment by AntiFish03** [comment]
@PikachuEXE, this would be the same issue if you tried to use `$` before you've loaded jQuery.  You have to load the library before it will work... Extending translations just means that instead of the translations stomping all over each other they can now be broken into smaller pieces and loaded with their respective components. It gives the ability to leverage smaller chunks at one time, And possibly load considerably less code per page that you might not actually be using.

As far as a way to turn it off or change the output to a template there are definitely ways to do that but I think that it would greatly increase the complexity of I18n-js even more than it is.  This is your project I submitted this change to try and help a project that I am using (and because I needed the ability to load smaller component sized translation files without them stomping all over each other).

**Comment by PikachuEXE** [comment]
Let me think about the best way to deal with this...
But I am too busy rushing on my job this week so you guys might need to wait for a while :S

**Comment by johnnyshields** [comment]
At a minimum we should make this new option configurable. Please merge my PR: https://github.com/fnando/i18n-js/pull/397

**Comment by PikachuEXE** [comment]
@johnnyshields I will review it on Monday
Thanks for the PR!

**Comment by PikachuEXE** [comment]
Can you all with this issue try `master` now since #397 is merged?

**Comment by johnnyshields** [comment]
Note on master to disable the extend you need to add:

```
js_extend: false
```

To the top of your I18n.yml.

**Comment by PikachuEXE** [comment]
@johnnyshields 
Seems easier to give them a link :P
https://github.com/fnando/i18n-js#javscript-deep-merge-js_extend-option

**Comment by rodrigobdz** [comment]
\* https://github.com/fnando/i18n-js#javascript-deep-merge-js_extend-option
