### ISSUE TITLE
Doesn't work with sprocket-rails v3.0

### ISSUE THREAD

**Issue by Sija** [fnando/i18n-js#378]
After doing `bundle update` my `sprocket-rails` dependency got updated to version `3.0.0` resulting in below error thrown by `i18n-js` gem:
```
/.../bundler/gems/i18n-js-c958d65cd5f5/lib/i18n/js/engine.rb:23:in `block in <class:Engine>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
```

**Comment by fsauter** [comment]
I can confirm this issue.

**Comment by PikachuEXE** [comment]
#376 Merged
Please try `master`

**Comment by Sija** [comment]
@PikachuEXE :+1: it works, thanks! :)

**Comment by dixpac** [comment]
Same problem for me, worked when used version from master.
@PikachuEXE  :+1:
